# Generated by Django 3.2.20 on 2023-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230823_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='txId',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
