# Generated by Django 3.2.20 on 2023-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230823_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='winner',
            field=models.CharField(max_length=50),
        ),
    ]
